country_language_dict = {
    'Afghanistan': ['Pashto', 'Dari', 'Uzbek'],
    'Albania': ['Albanian'],
    'Algeria': ['Arabic', 'Tamazight', 'French'],
    'Andorra': ['Catalan', 'Spanish'],
    'Angola': ['Portuguese'],
    'Antigua and Barbuda': ['English'],
    'Argentina': ['Spanish'],
    'Armenia': ['Armenian', 'Russian'],
    'Aruba': ['Dutch', 'Papiamento'],
    'Australia': ['English'],
    'Austria': ['German'],
    'Azerbaijan': ['Azerbaijani'],
    'The Bahamas': ['English'],
    'Bahrain': ['Arabic'],
    'Bangladesh': ['Bengali'],
    'Barbados': ['English'],
    'Belarus': ['Belarusian', 'Russian'],
    'Belgium': ['Dutch', 'French', 'German'],
    'Belize': ['English', 'Spanish'],
    'Benin': ['French'],
    'Bhutan': ['Dzongkha', 'English'],
    'Bolivia': ['Spanish', 'Quechua', 'Aymara'],
    'Bosnia and Herzegovina': ['Bosnian', 'Croatian', 'Serbian'],
    'Botswana': ['English', 'Setswana'],
    'Brazil': ['Portuguese'],
    'Brunei Darussalam': ['Malay'],
    'Bulgaria': ['Bulgarian'],
    'Burkina Faso': ['French'],
    'Burundi': ['Kirundi', 'French'],
    'Cabo Verde': ['Portuguese'],
    'Cambodia': ['Khmer'],
    'Cameroon': ['French', 'English'],
    'Canada': ['English', 'French'],
    'Central African Republic': ['French', 'Sango'],
    'Chad': ['French', 'Arabic'],
    'Chile': ['Spanish'],
    'China': ['Chinese (simplified)'],
    'Colombia': ['Spanish'],
    'Comoros': ['Comorian', 'Arabic', 'French'],
    'Democratic Republic of the Congo': ['French', 'Lingala', 'Swahili'],
    'Republic of Congo': ['French'],
    'Costa Rica': ['Spanish'],
    "Côte d'Ivoire": ['French'],
    'Croatia': ['Croatian'],
    'Cyprus': ['Greek', 'Turkish'],
    'Czech Republic': ['Czech'],
    'Denmark': ['Danish'],
    'Djibouti': ['French', 'Arabic'],
    'Dominica': ['English'],
    'Dominican Republic': ['Spanish'],
    'Ecuador': ['Spanish'],
    'Egypt': ['Arabic'],
    'El Salvador': ['Spanish'],
    'Equatorial Guinea': ['Spanish', 'French', 'Portuguese'],
    'Eritrea': ['Tigrinya', 'Arabic', 'English'],
    'Estonia': ['Estonian', 'Russian'],
    'Eswatini': ['Swati', 'English'],
    'Ethiopia': ['Amharic', 'Oromo', 'Tigrinya'],
    'Fiji': ['Fijian', 'English'],
    'Finland': ['Finnish', 'Swedish'],
    'France': ['French'],
    'Gabon': ['French'],
    'The Gambia': ['English'],
      'India': ['Hindi', 'Bengali', 'Telugu'],
  'Indonesia': ['Indonesian', 'Javanese', 'Sundanese'],
  'Iran, Islamic Republic of': ['Persian', 'Azerbaijani', 'Kurdish'],
  'Iraq': ['Arabic', 'Kurdish', 'Syriac'],
  'Ireland': ['Irish', 'English', 'Ulster Scots'],
  'Israel': ['Hebrew', 'Arabic', 'Russian'],
  'Italy': ['Italian', 'Sardinian', 'Sicilian'],
  'Jamaica': ['English', 'Jamaican Patois', 'Spanish'],
  'Japan': ['Japanese', 'Ainu', 'Ryukyuan'],
  'Jordan': ['Arabic', 'English', 'Armenian'],
  'Kazakhstan': ['Kazakh', 'Russian', 'Uzbek'],
  'Kenya': ['Swahili', 'English', 'Kikuyu'],
  'Kiribati': ['Gilbertese', 'English', 'Tuvaluan'],
  'Korea, Democratic People\'s Republic of': ['Korean'],
  'Korea, Republic of': ['Korean', 'English', 'Chinese (simplified)'],
  'Kosovo': ['Albanian', 'Serbian', 'Bosnian'],
  'Kuwait': ['Arabic', 'English'],
  'Kyrgyzstan': ['Kyrgyz', 'Russian', 'Uzbek'],
  'Lao People\'s Democratic Republic': ['Lao', 'French', 'English'],
  'Latvia': ['Latvian', 'Russian', 'Belarusian'],
  'Lebanon': ['Arabic', 'French', 'Armenian'],
  'Lesotho': ['Sesotho', 'English', 'Zulu'],
  'Liberia': ['English', 'Kpelle', 'Bassa'],
  'Libya': ['Arabic', 'Tamazight', 'English'],
  'Liechtenstein': ['German', 'Alemannic', 'Italian'],
  'Lithuania': ['Lithuanian', 'Russian', 'Polish'],
  'Luxembourg': ['Luxembourgish', 'German', 'French'],
  'Madagascar': ['Malagasy', 'French', 'English'],
  'Malawi': ['Chichewa', 'English', 'Lomwe'],
  'Malaysia': ['Malay', 'English', 'Chinese (simplified)'],
  'Maldives': ['Dhivehi', 'English'],
  'Mali': ['French', 'Bambara', 'Fula'],
  'Malta': ['Maltese', 'English', 'Italian'],
  'Marshall Islands': ['Marshallese', 'English', 'Japanese'],
  'Mauritania': ['Arabic', 'Pulaar', 'Soninke'],
  'Mauritius': ['Mauritian Creole', 'French', 'English'],
  'Mexico': ['Spanish', 'Nahuatl', 'Mayan'],
  'Micronesia, Federated States of': ['Chuukese', 'Pohnpeian', 'Kosraean'],
  'Moldova': ['Moldovan', 'Russian', 'Gagauz'],
  'Monaco': ['French', 'Monegasque', 'English'],
  'Mongolia': ['Mongolian', 'Kazakh', 'Russian'],
    'Montenegro': ['Montenegrin', 'Serbian', 'Bosnian'],
    'Morocco': ['Arabic', 'Berber', 'French'],
    'Mozambique': ['Portuguese', 'Makhuwa', 'Seneca'],
    'Myanmar': ['Myanmar (burmese)', 'Shan', 'Kayin'],
    'Namibia': ['English', 'Afrikaans', 'Oshiwambo'],
    'Nauru': ['Nauruan', 'English', 'Japanese'],
    'Nepal': ['Nepali', 'Maithili', 'Bhojpuri'],
    'Netherlands': ['Dutch', 'English', 'Papiamento'],
    'New Zealand': ['English', 'Maori', 'Samoan'],
    'Nicaragua': ['Spanish', 'Miskito', 'Creole'],
    'Niger': ['French', 'Hausa', 'Zarma'],
    'Nigeria': ['English', 'Yoruba', 'Igbo'],
    'North Macedonia': ['Macedonian', 'Albanian', 'Turkish'],
    'Norway': ['Norwegian', 'Sami', 'English'],
    'Oman': ['Arabic', 'Balochi', 'Swahili'],
    'Pakistan': ['Urdu', 'Punjabi', 'Sindhi'],
    'Palau': ['Palauan', 'English', 'Japanese'],
    'Panama': ['Spanish', 'Ngäbere', 'Buglere'],
    'Papua New Guinea': ['Tok Pisin', 'English', 'Hiri Motu'],
    'Paraguay': ['Guaraní', 'Spanish', 'Portuguese'],
    'Peru': ['Spanish', 'Quechua', 'Aymara'],
    'Philippines': ['Tagalog', 'Cebuano', 'Ilocano'],
    'Poland': ['Polish', 'Silesian', 'Kashubian'],
    'Portugal': ['Portuguese', 'Mirandese', 'Barranquenho'],
    'Puerto Rico': ['Spanish', 'English', 'Puerto Rican Sign Language'],
    'Qatar': ['Arabic', 'English', 'Urdu'],
    'Romania': ['Romanian', 'Hungarian', 'German'],
    'Russia': ['Russian', 'Tatar', 'Bashkir'],
    'Rwanda': ['Kinyarwanda', 'English', 'French'],
    'Samoa': ['Samoan', 'English', 'Tongan'],
    'San Marino': ['Italian', 'Romagnol', 'Sammarinese'],
    'São Tomé and Príncipe': ['Portuguese', 'Forro', 'Angolar'],
    'Saudi Arabia': ['Arabic', 'English', 'Urdu'],
    'Senegal': ['French', 'Wolof', 'Pulaar'],
    'Serbia': ['Serbian', 'Hungarian', 'Bosnian'],
    'Seychelles': ['Seychellois Creole', 'English', 'French'],
    'Sierra Leone': ['English', 'Krio', 'Mende'],
    'Singapore': ['English', 'Chinese (simplified)', 'Malay'],
    'Slovak Republic': ['Slovak', 'Hungarian', 'Romani'],
  'Slovenia': ['Slovene', 'Serbo-Croatian', 'Italian'],
  'Solomon Islands': ['English', 'Pidgin', 'Malaitan'],
  'Somalia': ['Somali', 'Arabic', 'Italian'],
  'South Africa': ['Zulu', 'Xhosa', 'Afrikaans'],
  'South Sudan': ['English', 'Dinka', 'Arabic'],
  'Spain': ['Spanish', 'Catalan', 'Galician'],
  'Sri Lanka': ['Sinhala', 'Tamil', 'English'],
  'St. Kitts and Nevis': ['English'],
  'St. Lucia': ['English', 'French Creole'],
  'St. Vincent and the Grenadines': ['English'],
  'Sudan': ['Arabic', 'English'],
  'Suriname': ['Dutch', 'Sranan Tongo', 'Hindi'],
  'Sweden': ['Swedish'],
  'Switzerland': ['German', 'French', 'Italian'],
  'Syria': ['Arabic', 'Kurdish', 'Armenian'],
  'Taiwan Province of China': ['Chinese (simplified)', 'Taiwanese Hokkien', 'Hakka'],
  'Tajikistan': ['Tajik', 'Russian'],
  'Tanzania': ['Swahili', 'English'],
  'Thailand': ['Thai', 'Isan', 'Chinese'],
  'Timor-Leste': ['Tetum', 'Portuguese', 'Indonesian'],
  'Togo': ['French', 'Ewe', 'Kabye'],
  'Tonga': ['Tongan', 'English'],
  'Trinidad and Tobago': ['English', 'Trinidadian Creole'],
  'Tunisia': ['Arabic', 'French'],
  'Türkiye': ['Turkish', 'Kurdish', 'Arabic'],
  'Turkmenistan': ['Turkmen', 'Russian'],
  'Tuvalu': ['Tuvaluan', 'English'],
  'Uganda': ['English', 'Swahili', 'Luganda'],
  'Ukraine': ['Ukrainian', 'Russian', 'Romanian'],
  'United Arab Emirates': ['Arabic', 'English', 'Urdu'],
  'United Kingdom': ['English', 'Welsh', 'Scottish Gaelic'],
  'United States': ['English', 'Spanish', 'Chinese'],
  'Uruguay': ['Spanish'],
  'Uzbekistan': ['Uzbek', 'Russian'],
  'Vanuatu': ['Bislama', 'English', 'French'],
  'Venezuela': ['Spanish'],
  'Vietnam': ['Vietnamese'],
  'West Bank and Gaza': ['Arabic', 'Hebrew'],
  'Yemen': ['Arabic'],
  'Zambia': ['Bemba', 'Nyanja', 'English'],
  'Zimbabwe': ['Shona', 'Ndebele', 'English']
  }

lang_codes = {
    'auto': 'Automatic',
    'af': 'Afrikaans',
    'sq': 'Albanian',
    'am': 'Amharic',
    'ar': 'Arabic',
    'hy': 'Armenian',
    'az': 'Azerbaijani',
    'eu': 'Basque',
    'be': 'Belarusian',
    'bn': 'Bengali',
    'bs': 'Bosnian',
    'bg': 'Bulgarian',
    'ca': 'Catalan',
    'ceb': 'Cebuano',
    'ny': 'Chichewa',
    'zh-cn': 'Chinese Simplified',
    'zh-tw': 'Chinese Traditional',
    'co': 'Corsican',
    'hr': 'Croatian',
    'cs': 'Czech',
    'da': 'Danish',
    'nl': 'Dutch',
    'en': 'English',
    'eo': 'Esperanto',
    'et': 'Estonian',
    'tl': 'Filipino',
    'fi': 'Finnish',
    'fr': 'French',
    'fy': 'Frisian',
    'gl': 'Galician',
    'ka': 'Georgian',
    'de': 'German',
    'el': 'Greek',
    'gu': 'Gujarati',
    'ht': 'Haitian Creole',
    'ha': 'Hausa',
    'haw': 'Hawaiian',
    'iw': 'Hebrew',
    'hi': 'Hindi',
    'hmn': 'Hmong',
    'hu': 'Hungarian',
    'is': 'Icelandic',
    'ig': 'Igbo',
    'id': 'Indonesian',
    'ga': 'Irish',
    'it': 'Italian',
    'ja': 'Japanese',
    'jw': 'Javanese',
    'kn': 'Kannada',
    'kk': 'Kazakh',
    'km': 'Khmer',
    'ko': 'Korean',
    'ku': 'Kurdish (Kurmanji)',
    'ky': 'Kyrgyz',
    'lo': 'Lao',
    'la': 'Latin',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'lb': 'Luxembourgish',
    'mk': 'Macedonian',
    'mg': 'Malagasy',
    'ms': 'Malay',
    'ml': 'Malayalam',
    'mt': 'Maltese',
    'mi': 'Maori',
    'mr': 'Marathi',
    'mn': 'Mongolian',
    'my': 'Myanmar (Burmese)',
    'ne': 'Nepali',
    'no': 'Norwegian',
    'ps': 'Pashto',
    'fa': 'Persian',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ma': 'Punjabi',
    'ro': 'Romanian',
    'ru': 'Russian',
    'sm': 'Samoan',
    'gd': 'Scots Gaelic',
    'sr': 'Serbian',
    'st': 'Sesotho',
    'sn': 'Shona',
    'sd': 'Sindhi',
    'si': 'Sinhala',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'so': 'Somali',
    'es': 'Spanish',
    'su': 'Sundanese',
    'sw': 'Swahili',
    'sv': 'Swedish',
    'tg': 'Tajik',
    'ta': 'Tamil',
    'te': 'Telugu',
    'th': 'Thai',
    'tr': 'Turkish',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'uz': 'Uzbek',
    'vi': 'Vietnamese',
    'cy': 'Welsh',
    'xh': 'Xhosa',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'zu': 'Zulu'
}
